In [1]:
import lbforaging
from games.foraging import Foraging 
import numpy as np
import time
from agents.random_agent import RandomAgent
from agents.independent_q_learning import IQL

In [2]:
game = Foraging(config=None)

c:\Users\marrt\miniconda3\envs\pettingzoo_games\Lib\site-packages\gymnasium\spaces\box.py:130: UserWarning: WARN: Box bound precision lowered by casting to float32
  gym.logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


In [3]:
game.reset()

#print game information
rewards = game.rewards
observations = game.observations
terminations = game.terminations
truncations = game.truncations
infos = game.infos
print("Game Information:")
print("Rewards: ", rewards)
print("Observations: ", observations)
print("Terminations: ", terminations)

print("Truncations: ", truncations)
print("Infos: ", infos)

Game Information:
Rewards:  {'agent_0': None, 'agent_1': None}
Observations:  {'agent_0': None, 'agent_1': None}
Terminations:  {'agent_0': False, 'agent_1': False}
Truncations:  {'agent_0': False, 'agent_1': False}
Infos:  {'agent_0': {}, 'agent_1': {}}


In [4]:
def run(game, agents, verbose=False, render=False):

    # Initialize the game
    game.reset()

    # Initialize rewards for each agent
    cum_rewards = dict(map(lambda agent: (agent, 0), game.agents))

    # render the game if required
    if render:
        game.render()
        time.sleep(0.5)

    while not game.done():

        # Get actions from each agent
        actions = dict(map(lambda agent: (agent, agents[agent].action()), game.agents))

        # Perform the actions in the game
        game.step(actions)

        # Update the cum_rewards for each agent
        for agent in game.agents:
            print(game.observe(agent))
            print(game.reward(agent))
            cum_rewards[agent] += game.reward(agent)

        # Print the rewards if verbose is enabled
        if verbose:
            for agent in game.agents:
                    print(f"Agent {agent} reward: {game.reward(agent)}")
                    print(f"Agent {agent} observe: {game.observe(agent)}")
            
        if render:
            game.render()
            time.sleep(0.5)
        
    return cum_rewards

In [5]:
run(game, {agent: IQL(game, agent) for agent in game.agents}, verbose=True, render=True)

c:\Users\marrt\miniconda3\envs\pettingzoo_games\Lib\site-packages\gymnasium\utils\passive_env_checker.py:275: UserWarning: WARN: The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'list'>
  logger.warn(


[2. 6. 2. 6. 1. 2. 0. 2. 2.]
0
[2. 6. 2. 0. 2. 2. 6. 1. 2.]
0
Agent agent_0 reward: 0
Agent agent_0 observe: [2. 6. 2. 6. 1. 2. 0. 2. 2.]
Agent agent_1 reward: 0
Agent agent_1 observe: [2. 6. 2. 0. 2. 2. 6. 1. 2.]
[2. 6. 2. 6. 1. 2. 0. 2. 2.]
0
[2. 6. 2. 0. 2. 2. 6. 1. 2.]
0
Agent agent_0 reward: 0
Agent agent_0 observe: [2. 6. 2. 6. 1. 2. 0. 2. 2.]
Agent agent_1 reward: 0
Agent agent_1 observe: [2. 6. 2. 0. 2. 2. 6. 1. 2.]
[2. 6. 2. 6. 1. 2. 0. 2. 2.]
0
[2. 6. 2. 0. 2. 2. 6. 1. 2.]
0
Agent agent_0 reward: 0
Agent agent_0 observe: [2. 6. 2. 6. 1. 2. 0. 2. 2.]
Agent agent_1 reward: 0
Agent agent_1 observe: [2. 6. 2. 0. 2. 2. 6. 1. 2.]
[2. 6. 2. 6. 1. 2. 0. 2. 2.]
0
[2. 6. 2. 0. 2. 2. 6. 1. 2.]
0
Agent agent_0 reward: 0
Agent agent_0 observe: [2. 6. 2. 6. 1. 2. 0. 2. 2.]
Agent agent_1 reward: 0
Agent agent_1 observe: [2. 6. 2. 0. 2. 2. 6. 1. 2.]
[2. 6. 2. 6. 1. 2. 0. 2. 2.]
0
[2. 6. 2. 0. 2. 2. 6. 1. 2.]
0
Agent agent_0 reward: 0
Agent agent_0 observe: [2. 6. 2. 6. 1. 2. 0. 2. 2.]
Agent 

{'agent_0': 0, 'agent_1': 0}